-- ! Don't edit this file as it is generated automatically !
{-# LANGUAGE OverloadedStrings #-}

module Carbon.Icons where

import Carbon.Icons.IconWatsonHealth3DCursor
import Carbon.Icons.IconWatsonHealth3DCursorAlt
import Carbon.Icons.IconWatsonHealth3DCurveAutoColon
import Carbon.Icons.IconWatsonHealth3DCurveAutoVessels
import Carbon.Icons.IconWatsonHealth3DCurveManual
import Carbon.Icons.IconWatsonHealth3DICa
import Carbon.Icons.IconWatsonHealth3DMprToggle
import Carbon.Icons.IconWatsonHealth3DPrintMesh
import Carbon.Icons.IconWatsonHealth3DSoftware
import Carbon.Icons.IconWatsonHealth3rdPartyConnected
import Carbon.Icons.Icon_4K
import Carbon.Icons.Icon_4KFilled
import Carbon.Icons.IconAccessibility
import Carbon.Icons.IconAccessibilityAlt
import Carbon.Icons.IconAccessibilityColor
import Carbon.Icons.IconAccessibilityColorFilled
import Carbon.Icons.IconAccount
import Carbon.Icons.IconAccumulationIce
import Carbon.Icons.IconAccumulationPrecipitation
import Carbon.Icons.IconAccumulationRain
import Carbon.Icons.IconAccumulationSnow
import Carbon.Icons.IconActivity
import Carbon.Icons.IconAdd
import Carbon.Icons.IconAddAlt
import Carbon.Icons.IconAddFilled
import Carbon.Icons.IconAddComment
import Carbon.Icons.IconAgricultureAnalytics
import Carbon.Icons.IconWatsonHealthAiResults
import Carbon.Icons.IconWatsonHealthAiResultsHigh
import Carbon.Icons.IconWatsonHealthAiResultsLow
import Carbon.Icons.IconWatsonHealthAiResultsMedium
import Carbon.Icons.IconWatsonHealthAiResultsUrgent
import Carbon.Icons.IconWatsonHealthAiResultsVeryHigh
import Carbon.Icons.IconWatsonHealthAiStatus
import Carbon.Icons.IconWatsonHealthAiStatusComplete
import Carbon.Icons.IconWatsonHealthAiStatusFailed
import Carbon.Icons.IconWatsonHealthAiStatusInProgress
import Carbon.Icons.IconWatsonHealthAiStatusQueued
import Carbon.Icons.IconWatsonHealthAiStatusRejected
import Carbon.Icons.IconAirlineDigitalGate
import Carbon.Icons.IconAirlineManageGates
import Carbon.Icons.IconAirlinePassengerCare
import Carbon.Icons.IconAirlineRapidBoard
import Carbon.Icons.IconAirport_01
import Carbon.Icons.IconAirport_02
import Carbon.Icons.IconAirportLocation
import Carbon.Icons.IconAlarm
import Carbon.Icons.IconAlarmAdd
import Carbon.Icons.IconAlarmSubtract
import Carbon.Icons.IconAlignHorizontalCenter
import Carbon.Icons.IconAlignHorizontalLeft
import Carbon.Icons.IconAlignHorizontalRight
import Carbon.Icons.IconAlignVerticalBottom
import Carbon.Icons.IconAlignVerticalCenter
import Carbon.Icons.IconAlignVerticalTop
import Carbon.Icons.IconAlignBoxBottomCenter
import Carbon.Icons.IconAlignBoxBottomLeft
import Carbon.Icons.IconAlignBoxBottomRight
import Carbon.Icons.IconAlignBoxMiddleCenter
import Carbon.Icons.IconAlignBoxMiddleLeft
import Carbon.Icons.IconAlignBoxMiddleRight
import Carbon.Icons.IconAlignBoxTopCenter
import Carbon.Icons.IconAlignBoxTopLeft
import Carbon.Icons.IconAlignBoxTopRight
import Carbon.Icons.IconAnalytics
import Carbon.Icons.IconAnalyticsReference
import Carbon.Icons.IconWatsonHealthAngle
import Carbon.Icons.IconWatsonHealthAnnotationVisibility
import Carbon.Icons.IconAperture
import Carbon.Icons.IconApi
import Carbon.Icons.IconApi_1
import Carbon.Icons.IconApp
import Carbon.Icons.IconAppConnectivity
import Carbon.Icons.IconAppSwitcher
import Carbon.Icons.IconApple
import Carbon.Icons.IconApplication
import Carbon.Icons.IconApps
import Carbon.Icons.IconArchive
import Carbon.Icons.IconArea
import Carbon.Icons.IconAreaCustom
import Carbon.Icons.IconArrival
import Carbon.Icons.IconWatsonHealthArrowAnnotation
import Carbon.Icons.IconArrowDown
import Carbon.Icons.IconArrowDownLeft
import Carbon.Icons.IconArrowDownRight
import Carbon.Icons.IconArrowLeft
import Carbon.Icons.IconArrowRight
import Carbon.Icons.IconArrowUp
import Carbon.Icons.IconArrowUpLeft
import Carbon.Icons.IconArrowUpRight
import Carbon.Icons.IconArrowShiftDown
import Carbon.Icons.IconArrows
import Carbon.Icons.IconArrowsHorizontal
import Carbon.Icons.IconArrowsVertical
import Carbon.Icons.IconAsleep
import Carbon.Icons.IconAsleepFilled
import Carbon.Icons.IconAsset
import Carbon.Icons.IconAt
import Carbon.Icons.IconAttachment
import Carbon.Icons.IconAudioConsole
import Carbon.Icons.IconAugmentedReality
import Carbon.Icons.IconWatsonHealthAutoScroll
import Carbon.Icons.IconAutomatic
import Carbon.Icons.IconAwake
import Carbon.Icons.IconBackToTop
import Carbon.Icons.IconBadge
import Carbon.Icons.IconBaggageClaim
import Carbon.Icons.IconBar
import Carbon.Icons.IconBarcode
import Carbon.Icons.IconQBarrier
import Carbon.Icons.IconBasketball
import Carbon.Icons.IconBat
import Carbon.Icons.IconBatteryCharging
import Carbon.Icons.IconBatteryEmpty
import Carbon.Icons.IconBatteryFull
import Carbon.Icons.IconBatteryHalf
import Carbon.Icons.IconBatteryLow
import Carbon.Icons.IconBatteryQuarter
import Carbon.Icons.IconBee
import Carbon.Icons.IconBeeBat
import Carbon.Icons.IconBicycle
import Carbon.Icons.IconBinoculars
import Carbon.Icons.IconQBlochSphere
import Carbon.Icons.IconBlockchain
import Carbon.Icons.IconBlog
import Carbon.Icons.IconBluetooth
import Carbon.Icons.IconBluetoothOff
import Carbon.Icons.IconBook
import Carbon.Icons.IconBookmark
import Carbon.Icons.IconBookmarkFilled
import Carbon.Icons.IconBoolean
import Carbon.Icons.IconBorderBottom
import Carbon.Icons.IconBorderFull
import Carbon.Icons.IconBorderLeft
import Carbon.Icons.IconBorderNone
import Carbon.Icons.IconBorderRight
import Carbon.Icons.IconBorderTop
import Carbon.Icons.IconBot
import Carbon.Icons.IconBox
import Carbon.Icons.IconBoxPlot
import Carbon.Icons.IconBranch
import Carbon.Icons.IconBrightnessContrast
import Carbon.Icons.IconBringToFront
import Carbon.Icons.IconWatsonHealthBrushFreehand
import Carbon.Icons.IconWatsonHealthBrushPolygon
import Carbon.Icons.IconBuilding
import Carbon.Icons.IconBuildingInsights_1
import Carbon.Icons.IconBuildingInsights_2
import Carbon.Icons.IconBuildingInsights_3
import Carbon.Icons.IconBullhorn
import Carbon.Icons.IconBuoy
import Carbon.Icons.IconBus
import Carbon.Icons.IconCabinCare
import Carbon.Icons.IconCabinCareAlert
import Carbon.Icons.IconCabinCareAlt
import Carbon.Icons.IconCad
import Carbon.Icons.IconCafe
import Carbon.Icons.IconCalculation
import Carbon.Icons.IconCalculationAlt
import Carbon.Icons.IconCalculator
import Carbon.Icons.IconCalculatorCheck
import Carbon.Icons.IconCalendar
import Carbon.Icons.IconCalendarHeatMap
import Carbon.Icons.IconCalendarSettings
import Carbon.Icons.IconCalendarTools
import Carbon.Icons.IconCalibrate
import Carbon.Icons.IconCamera
import Carbon.Icons.IconCameraAction
import Carbon.Icons.IconCampsite
import Carbon.Icons.IconCar
import Carbon.Icons.IconCarFront
import Carbon.Icons.IconCarbon
import Carbon.Icons.IconCaretDown
import Carbon.Icons.IconCaretLeft
import Carbon.Icons.IconCaretRight
import Carbon.Icons.IconCaretSort
import Carbon.Icons.IconCaretSortDown
import Carbon.Icons.IconCaretSortUp
import Carbon.Icons.IconCaretUp
import Carbon.Icons.IconCarouselHorizontal
import Carbon.Icons.IconCarouselVertical
import Carbon.Icons.IconCatalog
import Carbon.Icons.IconCategories
import Carbon.Icons.IconCategory
import Carbon.Icons.IconCategoryAdd
import Carbon.Icons.IconCategoryAnd
import Carbon.Icons.IconCategoryNew
import Carbon.Icons.IconCategoryNewEach
import Carbon.Icons.IconQCcX
import Carbon.Icons.IconWatsonHealthCdArchive
import Carbon.Icons.IconWatsonHealthCdCreateArchive
import Carbon.Icons.IconWatsonHealthCdCreateExchange
import Carbon.Icons.IconCda
import Carbon.Icons.IconCenterCircle
import Carbon.Icons.IconCenterSquare
import Carbon.Icons.IconCenterToFit
import Carbon.Icons.IconCertificate
import Carbon.Icons.IconCertificateCheck
import Carbon.Icons.IconChangeCatalog
import Carbon.Icons.IconCharacterPatterns
import Carbon.Icons.IconChargingStation
import Carbon.Icons.IconChargingStationFilled
import Carbon.Icons.IconChart_3D
import Carbon.Icons.IconChartArea
import Carbon.Icons.IconChartAreaSmooth
import Carbon.Icons.IconChartAreaStepper
import Carbon.Icons.IconChartAverage
import Carbon.Icons.IconChartBar
import Carbon.Icons.IconChartBarFloating
import Carbon.Icons.IconChartBarOverlay
import Carbon.Icons.IconChartBarStacked
import Carbon.Icons.IconChartBarTarget
import Carbon.Icons.IconChartBubble
import Carbon.Icons.IconChartBubblePacked
import Carbon.Icons.IconChartBullet
import Carbon.Icons.IconChartCandlestick
import Carbon.Icons.IconChartClusterBar
import Carbon.Icons.IconChartColumn
import Carbon.Icons.IconChartColumnFloating
import Carbon.Icons.IconChartColumnTarget
import Carbon.Icons.IconChartCombo
import Carbon.Icons.IconChartComboStacked
import Carbon.Icons.IconChartCustom
import Carbon.Icons.IconChartErrorBar
import Carbon.Icons.IconChartErrorBarAlt
import Carbon.Icons.IconChartEvaluation
import Carbon.Icons.IconChartHighLow
import Carbon.Icons.IconChartHistogram
import Carbon.Icons.IconChartLine
import Carbon.Icons.IconChartLineData
import Carbon.Icons.IconChartLineSmooth
import Carbon.Icons.IconChartMarimekko
import Carbon.Icons.IconChartMaximum
import Carbon.Icons.IconChartMedian
import Carbon.Icons.IconChartMinimum
import Carbon.Icons.IconChartMultiLine
import Carbon.Icons.IconChartMultitype
import Carbon.Icons.IconChartNetwork
import Carbon.Icons.IconChartParallel
import Carbon.Icons.IconChartPie
import Carbon.Icons.IconChartPoint
import Carbon.Icons.IconChartPopulation
import Carbon.Icons.IconChartRadar
import Carbon.Icons.IconChartRadial
import Carbon.Icons.IconChartRelationship
import Carbon.Icons.IconChartRing
import Carbon.Icons.IconChartRiver
import Carbon.Icons.IconChartRose
import Carbon.Icons.IconChartScatter
import Carbon.Icons.IconChartSpiral
import Carbon.Icons.IconChartStacked
import Carbon.Icons.IconChartStepper
import Carbon.Icons.IconChartSunburst
import Carbon.Icons.IconChartTSne
import Carbon.Icons.IconChartTreemap
import Carbon.Icons.IconChartVennDiagram
import Carbon.Icons.IconChartViolinPlot
import Carbon.Icons.IconChartWaterfall
import Carbon.Icons.IconChartWinLoss
import Carbon.Icons.IconChat
import Carbon.Icons.IconChatBot
import Carbon.Icons.IconCheckbox
import Carbon.Icons.IconCheckboxChecked
import Carbon.Icons.IconCheckboxCheckedFilled
import Carbon.Icons.IconCheckboxIndeterminate
import Carbon.Icons.IconCheckboxIndeterminateFilled
import Carbon.Icons.IconCheckboxUndeterminate
import Carbon.Icons.IconCheckboxUndeterminateFilled
import Carbon.Icons.IconCheckmark
import Carbon.Icons.IconCheckmarkFilled
import Carbon.Icons.IconCheckmarkFilledError
import Carbon.Icons.IconCheckmarkFilledWarning
import Carbon.Icons.IconCheckmarkOutline
import Carbon.Icons.IconCheckmarkOutlineError
import Carbon.Icons.IconCheckmarkOutlineWarning
import Carbon.Icons.IconChemistry
import Carbon.Icons.IconChemistryReference
import Carbon.Icons.IconChevronDown
import Carbon.Icons.IconChevronLeft
import Carbon.Icons.IconChevronMini
import Carbon.Icons.IconChevronRight
import Carbon.Icons.IconChevronSort
import Carbon.Icons.IconChevronSortDown
import Carbon.Icons.IconChevronSortUp
import Carbon.Icons.IconChevronUp
import Carbon.Icons.IconChip
import Carbon.Icons.IconChoices
import Carbon.Icons.IconChoroplethMap
import Carbon.Icons.IconCircleFilled
import Carbon.Icons.IconCircleDash
import Carbon.Icons.IconWatsonHealthCircleMeasurement
import Carbon.Icons.IconCirclePacking
import Carbon.Icons.IconQCircuitComposer
import Carbon.Icons.IconClassification
import Carbon.Icons.IconClassifierLanguage
import Carbon.Icons.IconClean
import Carbon.Icons.IconClose
import Carbon.Icons.IconCloseFilled
import Carbon.Icons.IconCloseOutline
import Carbon.Icons.IconClosedCaption
import Carbon.Icons.IconClosedCaptionAlt
import Carbon.Icons.IconClosedCaptionFilled
import Carbon.Icons.IconCloud
import Carbon.Icons.IconCloudDataOps
import Carbon.Icons.IconCloudDownload
import Carbon.Icons.IconCloudLightning
import Carbon.Icons.IconCloudRain
import Carbon.Icons.IconCloudSnow
import Carbon.Icons.IconCloudUpload
import Carbon.Icons.IconCloudApp
import Carbon.Icons.IconCloudCeiling
import Carbon.Icons.IconCloudFoundry_1
import Carbon.Icons.IconCloudFoundry_2
import Carbon.Icons.IconCloudSatellite
import Carbon.Icons.IconCloudy
import Carbon.Icons.IconWatsonHealthCobbAngle
import Carbon.Icons.IconCode
import Carbon.Icons.IconCodeHide
import Carbon.Icons.IconCodeReference
import Carbon.Icons.IconCognitive
import Carbon.Icons.IconCollaborate
import Carbon.Icons.IconCollapseAll
import Carbon.Icons.IconCollapseCategories
import Carbon.Icons.IconColorPalette
import Carbon.Icons.IconColorSwitch
import Carbon.Icons.IconColumn
import Carbon.Icons.IconColumnDelete
import Carbon.Icons.IconColumnInsert
import Carbon.Icons.IconColumnDependency
import Carbon.Icons.IconCommit
import Carbon.Icons.IconCompare
import Carbon.Icons.IconCompass
import Carbon.Icons.IconQComposerEdit
import Carbon.Icons.IconConcept
import Carbon.Icons.IconConnect
import Carbon.Icons.IconConnectionSignal
import Carbon.Icons.IconConnectionSignalOff
import Carbon.Icons.IconConstruction
import Carbon.Icons.IconContainerSoftware
import Carbon.Icons.IconContentView
import Carbon.Icons.IconWatsonHealthContourFinding
import Carbon.Icons.IconContrast
import Carbon.Icons.IconCopy
import Carbon.Icons.IconCopyFile
import Carbon.Icons.IconCopyLink
import Carbon.Icons.IconCorn
import Carbon.Icons.IconCorner
import Carbon.Icons.IconCoronavirus
import Carbon.Icons.IconCourse
import Carbon.Icons.IconCovariate
import Carbon.Icons.IconCredentials
import Carbon.Icons.IconCrop
import Carbon.Icons.IconCropGrowth
import Carbon.Icons.IconCropHealth
import Carbon.Icons.IconWatsonHealthCrossReference
import Carbon.Icons.IconCrossTab
import Carbon.Icons.IconCrossroads
import Carbon.Icons.IconCrowdReport
import Carbon.Icons.IconCrowdReportFilled
import Carbon.Icons.IconCsv
import Carbon.Icons.IconQCU1
import Carbon.Icons.IconQCU3
import Carbon.Icons.IconCube
import Carbon.Icons.IconCubeView
import Carbon.Icons.IconCurrencyBaht
import Carbon.Icons.IconCurrencyDollar
import Carbon.Icons.IconCurrencyEuro
import Carbon.Icons.IconCurrencyLira
import Carbon.Icons.IconCurrencyPound
import Carbon.Icons.IconCurrencyRupee
import Carbon.Icons.IconCurrencyShekel
import Carbon.Icons.IconCurrencyWon
import Carbon.Icons.IconCurrencyYen
import Carbon.Icons.IconCursor_1
import Carbon.Icons.IconCursor_2
import Carbon.Icons.IconCut
import Carbon.Icons.IconWatsonHealthCutInHalf
import Carbon.Icons.IconQCY
import Carbon.Icons.IconCyclist
import Carbon.Icons.IconQCZ
import Carbon.Icons.IconDashboard
import Carbon.Icons.IconDashboardReference
import Carbon.Icons.IconData_1
import Carbon.Icons.IconData_2
import Carbon.Icons.IconDataBase
import Carbon.Icons.IconDataBaseAlt
import Carbon.Icons.IconDataCheck
import Carbon.Icons.IconDataConnected
import Carbon.Icons.IconDataError
import Carbon.Icons.IconDataFormat
import Carbon.Icons.IconDataReference
import Carbon.Icons.IconDataSet
import Carbon.Icons.IconDataStructured
import Carbon.Icons.IconDataUnstructured
import Carbon.Icons.IconDataView
import Carbon.Icons.IconDataBin
import Carbon.Icons.IconDataClass
import Carbon.Icons.IconDataCollection
import Carbon.Icons.IconDataPlayer
import Carbon.Icons.IconDataRefinery
import Carbon.Icons.IconDataRefineryReference
import Carbon.Icons.IconDataShare
import Carbon.Icons.IconDataTable
import Carbon.Icons.IconDataTableReference
import Carbon.Icons.IconDataVis_1
import Carbon.Icons.IconDataVis_2
import Carbon.Icons.IconDataVis_3
import Carbon.Icons.IconDataVis_4
import Carbon.Icons.IconDatastore
import Carbon.Icons.IconDebug
import Carbon.Icons.IconDecisionTree
import Carbon.Icons.IconDelete
import Carbon.Icons.IconDeliveryParcel
import Carbon.Icons.IconDelivery
import Carbon.Icons.IconDeliveryTruck
import Carbon.Icons.IconWatsonHealthDenominate
import Carbon.Icons.IconDeparture
import Carbon.Icons.IconDeploy
import Carbon.Icons.IconDeployRules
import Carbon.Icons.IconDeploymentPattern
import Carbon.Icons.IconDeploymentPolicy
import Carbon.Icons.IconDevelopment
import Carbon.Icons.IconDevices
import Carbon.Icons.IconDewPoint
import Carbon.Icons.IconDewPointFilled
import Carbon.Icons.IconDiagram
import Carbon.Icons.IconDiagramReference
import Carbon.Icons.IconWatsonHealthDicom_6000
import Carbon.Icons.IconWatsonHealthDicomOverlay
import Carbon.Icons.IconDirectionBearRight_01
import Carbon.Icons.IconDirectionBearRight_01Filled
import Carbon.Icons.IconDirectionBearRight_02
import Carbon.Icons.IconDirectionBearRight_02Filled
import Carbon.Icons.IconDirectionCurve
import Carbon.Icons.IconDirectionCurveFilled
import Carbon.Icons.IconDirectionFork
import Carbon.Icons.IconDirectionForkFilled
import Carbon.Icons.IconDirectionLoopLeft
import Carbon.Icons.IconDirectionLoopLeftFilled
import Carbon.Icons.IconDirectionLoopRight
import Carbon.Icons.IconDirectionLoopRightFilled
import Carbon.Icons.IconDirectionMerge
import Carbon.Icons.IconDirectionMergeFilled
import Carbon.Icons.IconDirectionRight_01
import Carbon.Icons.IconDirectionRight_01Filled
import Carbon.Icons.IconDirectionRight_02
import Carbon.Icons.IconDirectionRight_02Filled
import Carbon.Icons.IconDirectionRotaryFirstRight
import Carbon.Icons.IconDirectionRotaryFirstRightFilled
import Carbon.Icons.IconDirectionRotaryRight
import Carbon.Icons.IconDirectionRotaryRightFilled
import Carbon.Icons.IconDirectionRotaryStraight
import Carbon.Icons.IconDirectionRotaryStraightFilled
import Carbon.Icons.IconDirectionSharpTurn
import Carbon.Icons.IconDirectionSharpTurnFilled
import Carbon.Icons.IconDirectionStraight
import Carbon.Icons.IconDirectionStraightFilled
import Carbon.Icons.IconDirectionStraightRight
import Carbon.Icons.IconDirectionStraightRightFilled
import Carbon.Icons.IconDirectionUTurn
import Carbon.Icons.IconDirectionUTurnFilled
import Carbon.Icons.IconDistributeHorizontalCenter
import Carbon.Icons.IconDistributeHorizontalLeft
import Carbon.Icons.IconDistributeHorizontalRight
import Carbon.Icons.IconDistributeVerticalBottom
import Carbon.Icons.IconDistributeVerticalCenter
import Carbon.Icons.IconDistributeVerticalTop
import Carbon.Icons.IconWatsonHealthDna
import Carbon.Icons.IconDoc
import Carbon.Icons.IconDocument
import Carbon.Icons.IconDocumentAdd
import Carbon.Icons.IconDocumentBlank
import Carbon.Icons.IconDocumentDownload
import Carbon.Icons.IconDocumentExport
import Carbon.Icons.IconDocumentHorizontal
import Carbon.Icons.IconDocumentImport
import Carbon.Icons.IconDocumentPdf
import Carbon.Icons.IconDocumentSubtract
import Carbon.Icons.IconDocumentTasks
import Carbon.Icons.IconDocumentUnknown
import Carbon.Icons.IconDocumentVertical
import Carbon.Icons.IconDocumentView
import Carbon.Icons.IconDocumentWordProcessor
import Carbon.Icons.IconDocumentWordProcessorReference
import Carbon.Icons.IconDocumentSentiment
import Carbon.Icons.IconDotMark
import Carbon.Icons.IconDoubleInteger
import Carbon.Icons.IconDownToBottom
import Carbon.Icons.IconDownload
import Carbon.Icons.IconWatsonHealthDownloadStudy
import Carbon.Icons.IconDragHorizontal
import Carbon.Icons.IconDragVertical
import Carbon.Icons.IconDraggable
import Carbon.Icons.IconDraw
import Carbon.Icons.IconDrillBack
import Carbon.Icons.IconDrillDown
import Carbon.Icons.IconDrillThrough
import Carbon.Icons.IconDriverAnalysis
import Carbon.Icons.IconDropPhoto
import Carbon.Icons.IconDropPhotoFilled
import Carbon.Icons.IconDrought
import Carbon.Icons.IconDvr
import Carbon.Icons.IconEarth
import Carbon.Icons.IconEarthAmericas
import Carbon.Icons.IconEarthAmericasFilled
import Carbon.Icons.IconEarthEuropeAfrica
import Carbon.Icons.IconEarthEuropeAfricaFilled
import Carbon.Icons.IconEarthFilled
import Carbon.Icons.IconEarthSoutheastAsia
import Carbon.Icons.IconEarthSoutheastAsiaFilled
import Carbon.Icons.IconEarthquake
import Carbon.Icons.IconEdgeCluster
import Carbon.Icons.IconEdgeDevice
import Carbon.Icons.IconWatsonHealthEdgeEnhancement
import Carbon.Icons.IconWatsonHealthEdgeEnhancement_01
import Carbon.Icons.IconWatsonHealthEdgeEnhancement_02
import Carbon.Icons.IconWatsonHealthEdgeEnhancement_03
import Carbon.Icons.IconEdgeNode
import Carbon.Icons.IconEdgeService
import Carbon.Icons.IconEdit
import Carbon.Icons.IconEditOff
import Carbon.Icons.IconWatsonHealthEditFilter
import Carbon.Icons.IconEdtLoop
import Carbon.Icons.IconEducation
import Carbon.Icons.IconEmail
import Carbon.Icons.IconEmailNew
import Carbon.Icons.IconEnterprise
import Carbon.Icons.IconEqualizer
import Carbon.Icons.IconErase
import Carbon.Icons.IconWatsonHealthErase_3D
import Carbon.Icons.IconError
import Carbon.Icons.IconErrorFilled
import Carbon.Icons.IconErrorOutline
import Carbon.Icons.IconEvent
import Carbon.Icons.IconEventSchedule
import Carbon.Icons.IconEvents
import Carbon.Icons.IconEventsAlt
import Carbon.Icons.IconExamMode
import Carbon.Icons.IconExit
import Carbon.Icons.IconExpandAll
import Carbon.Icons.IconExpandCategories
import Carbon.Icons.IconExplore
import Carbon.Icons.IconExport
import Carbon.Icons.IconEyedropper
import Carbon.Icons.IconFaceActivated
import Carbon.Icons.IconFaceActivatedAdd
import Carbon.Icons.IconFaceActivatedFilled
import Carbon.Icons.IconFaceAdd
import Carbon.Icons.IconFaceCool
import Carbon.Icons.IconFaceDissatisfied
import Carbon.Icons.IconFaceDissatisfiedFilled
import Carbon.Icons.IconFaceDizzy
import Carbon.Icons.IconFaceDizzyFilled
import Carbon.Icons.IconFaceMask
import Carbon.Icons.IconFaceNeutral
import Carbon.Icons.IconFaceNeutralFilled
import Carbon.Icons.IconFacePending
import Carbon.Icons.IconFacePendingFilled
import Carbon.Icons.IconFaceSatisfied
import Carbon.Icons.IconFaceSatisfiedFilled
import Carbon.Icons.IconFaceWink
import Carbon.Icons.IconFaceWinkFilled
import Carbon.Icons.IconFactor
import Carbon.Icons.IconFade
import Carbon.Icons.IconFavorite
import Carbon.Icons.IconFavoriteFilled
import Carbon.Icons.IconFavoriteHalf
import Carbon.Icons.IconFetchUpload
import Carbon.Icons.IconFetchUploadCloud
import Carbon.Icons.IconFilter
import Carbon.Icons.IconFilterEdit
import Carbon.Icons.IconFilterRemove
import Carbon.Icons.IconFilterReset
import Carbon.Icons.IconFinance
import Carbon.Icons.IconFingerprintRecognition
import Carbon.Icons.IconFire
import Carbon.Icons.IconFish
import Carbon.Icons.IconFishMultiple
import Carbon.Icons.IconFitToScreen
import Carbon.Icons.IconFlag
import Carbon.Icons.IconFlagFilled
import Carbon.Icons.IconFlaggingTaxi
import Carbon.Icons.IconFlash
import Carbon.Icons.IconFlashFilled
import Carbon.Icons.IconFlashOff
import Carbon.Icons.IconFlashOffFilled
import Carbon.Icons.IconFlightInternational
import Carbon.Icons.IconFlightRoster
import Carbon.Icons.IconFlightSchedule
import Carbon.Icons.IconFlood
import Carbon.Icons.IconFloodWarning
import Carbon.Icons.IconFlow
import Carbon.Icons.IconFlowConnection
import Carbon.Icons.IconFlowData
import Carbon.Icons.IconFlowModeler
import Carbon.Icons.IconFlowStream
import Carbon.Icons.IconFlowStreamReference
import Carbon.Icons.IconFog
import Carbon.Icons.IconFolder
import Carbon.Icons.IconFolderAdd
import Carbon.Icons.IconFolderDetails
import Carbon.Icons.IconFolderDetailsReference
import Carbon.Icons.IconFolderMoveTo
import Carbon.Icons.IconFolderOff
import Carbon.Icons.IconFolderShared
import Carbon.Icons.IconFolders
import Carbon.Icons.IconForecastHail
import Carbon.Icons.IconForecastHail_30
import Carbon.Icons.IconForecastLightning
import Carbon.Icons.IconForecastLightning_30
import Carbon.Icons.IconFork
import Carbon.Icons.IconForum
import Carbon.Icons.IconForward_10
import Carbon.Icons.IconForward_30
import Carbon.Icons.IconForward_5
import Carbon.Icons.IconFragile
import Carbon.Icons.IconFruitBowl
import Carbon.Icons.IconFunction
import Carbon.Icons.IconFunctionMath
import Carbon.Icons.IconWatsonHealthFusionBlender
import Carbon.Icons.IconGameConsole
import Carbon.Icons.IconGameWireless
import Carbon.Icons.IconGamification
import Carbon.Icons.IconGasStation
import Carbon.Icons.IconGasStationFilled
import Carbon.Icons.IconGenderFemale
import Carbon.Icons.IconGenderMale
import Carbon.Icons.IconGeneratePdf
import Carbon.Icons.IconGif
import Carbon.Icons.IconGift
import Carbon.Icons.IconGlobe
import Carbon.Icons.IconGradient
import Carbon.Icons.IconGraphicalDataFlow
import Carbon.Icons.IconGrid
import Carbon.Icons.IconGroup
import Carbon.Icons.IconQH
import Carbon.Icons.IconHail
import Carbon.Icons.IconWatsonHealthHangingProtocol
import Carbon.Icons.IconHarbor
import Carbon.Icons.IconHashtag
import Carbon.Icons.IconHaze
import Carbon.Icons.IconHazeNight
import Carbon.Icons.IconHd
import Carbon.Icons.IconHdFilled
import Carbon.Icons.IconHdr
import Carbon.Icons.IconHeadphones
import Carbon.Icons.IconHeadset
import Carbon.Icons.IconHealthCross
import Carbon.Icons.IconHearing
import Carbon.Icons.IconHeatMap
import Carbon.Icons.IconHeatMap_02
import Carbon.Icons.IconHeatMap_03
import Carbon.Icons.IconHeatMapStocks
import Carbon.Icons.IconHelicopter
import Carbon.Icons.IconHelp
import Carbon.Icons.IconHelpFilled
import Carbon.Icons.IconHelpDesk
import Carbon.Icons.IconQHintonPlot
import Carbon.Icons.IconWatsonHealthHoleFilling
import Carbon.Icons.IconWatsonHealthHoleFillingCursor
import Carbon.Icons.IconHome
import Carbon.Icons.IconHospital
import Carbon.Icons.IconHospitalBed
import Carbon.Icons.IconHotel
import Carbon.Icons.IconHourglass
import Carbon.Icons.IconHtml
import Carbon.Icons.IconHtmlReference
import Carbon.Icons.IconHttp
import Carbon.Icons.IconHumidity
import Carbon.Icons.IconHumidityAlt
import Carbon.Icons.IconHurricane
import Carbon.Icons.IconHybridNetworking
import Carbon.Icons.IconIbmCloud
import Carbon.Icons.IconIbmSecurity
import Carbon.Icons.IconWatsonHealthICa_2D
import Carbon.Icons.IconIceAccretion
import Carbon.Icons.IconQID
import Carbon.Icons.IconIdea
import Carbon.Icons.IconIdentification
import Carbon.Icons.IconImage
import Carbon.Icons.IconImageMedical
import Carbon.Icons.IconImageReference
import Carbon.Icons.IconImageSearch
import Carbon.Icons.IconImproveRelevance
import Carbon.Icons.IconInProgress
import Carbon.Icons.IconInProgressError
import Carbon.Icons.IconInProgressWarning
import Carbon.Icons.IconIncomplete
import Carbon.Icons.IconIncompleteCancel
import Carbon.Icons.IconIncompleteError
import Carbon.Icons.IconIncompleteWarning
import Carbon.Icons.IconIncreaseLevel
import Carbon.Icons.IconIndustry
import Carbon.Icons.IconInformation
import Carbon.Icons.IconInformationFilled
import Carbon.Icons.IconInformationSquare
import Carbon.Icons.IconInformationSquareFilled
import Carbon.Icons.IconInsert
import Carbon.Icons.IconInsertPage
import Carbon.Icons.IconInsertSyntax
import Carbon.Icons.IconIntegration
import Carbon.Icons.IconInteractions
import Carbon.Icons.IconWatsonHealthInteractiveSegmentationCursor
import Carbon.Icons.IconIntersect
import Carbon.Icons.IconInventoryManagement
import Carbon.Icons.IconIotConnect
import Carbon.Icons.IconIotPlatform
import Carbon.Icons.IconIso
import Carbon.Icons.IconIsoFilled
import Carbon.Icons.IconIsoOutline
import Carbon.Icons.IconJoinFull
import Carbon.Icons.IconJoinInner
import Carbon.Icons.IconJoinLeft
import Carbon.Icons.IconJoinOuter
import Carbon.Icons.IconJoinRight
import Carbon.Icons.IconJpg
import Carbon.Icons.IconJson
import Carbon.Icons.IconJsonReference
import Carbon.Icons.IconJumpLink
import Carbon.Icons.IconKeepDry
import Carbon.Icons.IconKeyboard
import Carbon.Icons.IconLanguage
import Carbon.Icons.IconLaptop
import Carbon.Icons.IconLasso
import Carbon.Icons.IconLassoPolygon
import Carbon.Icons.IconLaunch
import Carbon.Icons.IconWatsonHealthLaunchStudy_1
import Carbon.Icons.IconWatsonHealthLaunchStudy_2
import Carbon.Icons.IconWatsonHealthLaunchStudy_3
import Carbon.Icons.IconLayers
import Carbon.Icons.IconLegend
import Carbon.Icons.IconLetterAa
import Carbon.Icons.IconLetterBb
import Carbon.Icons.IconLetterCc
import Carbon.Icons.IconLetterDd
import Carbon.Icons.IconLetterEe
import Carbon.Icons.IconLetterFf
import Carbon.Icons.IconLetterGg
import Carbon.Icons.IconLetterHh
import Carbon.Icons.IconLetterIi
import Carbon.Icons.IconLetterJj
import Carbon.Icons.IconLetterKk
import Carbon.Icons.IconLetterLl
import Carbon.Icons.IconLetterMm
import Carbon.Icons.IconLetterNn
import Carbon.Icons.IconLetterOo
import Carbon.Icons.IconLetterPp
import Carbon.Icons.IconLetterQq
import Carbon.Icons.IconLetterRr
import Carbon.Icons.IconLetterSs
import Carbon.Icons.IconLetterTt
import Carbon.Icons.IconLetterUu
import Carbon.Icons.IconLetterVv
import Carbon.Icons.IconLetterWw
import Carbon.Icons.IconLetterXx
import Carbon.Icons.IconLetterYy
import Carbon.Icons.IconLetterZz
import Carbon.Icons.IconLicense
import Carbon.Icons.IconLicenseDraft
import Carbon.Icons.IconLicenseGlobal
import Carbon.Icons.IconLicenseMaintenance
import Carbon.Icons.IconLicenseMaintenanceDraft
import Carbon.Icons.IconLicenseThirdParty
import Carbon.Icons.IconLicenseThirdPartyDraft
import Carbon.Icons.IconLight
import Carbon.Icons.IconLightFilled
import Carbon.Icons.IconLightning
import Carbon.Icons.IconLink
import Carbon.Icons.IconLinux
import Carbon.Icons.IconLinuxAlt
import Carbon.Icons.IconList
import Carbon.Icons.IconListBoxes
import Carbon.Icons.IconListBulleted
import Carbon.Icons.IconListChecked
import Carbon.Icons.IconListDropdown
import Carbon.Icons.IconListNumbered
import Carbon.Icons.IconLocation
import Carbon.Icons.IconLocationCompany
import Carbon.Icons.IconLocationCompanyFilled
import Carbon.Icons.IconLocationCurrent
import Carbon.Icons.IconLocationHazard
import Carbon.Icons.IconLocationHazardFilled
import Carbon.Icons.IconLocationHeart
import Carbon.Icons.IconLocationHeartFilled
import Carbon.Icons.IconLocationPerson
import Carbon.Icons.IconLocationPersonFilled
import Carbon.Icons.IconLocationStar
import Carbon.Icons.IconLocationStarFilled
import Carbon.Icons.IconLocked
import Carbon.Icons.IconLogin
import Carbon.Icons.IconLogoDigg
import Carbon.Icons.IconLogoFacebook
import Carbon.Icons.IconLogoFlickr
import Carbon.Icons.IconLogoGithub
import Carbon.Icons.IconLogoGlassdoor
import Carbon.Icons.IconLogoInstagram
import Carbon.Icons.IconLogoJupyter
import Carbon.Icons.IconLogoKeybase
import Carbon.Icons.IconLogoLinkedin
import Carbon.Icons.IconLogoLivestream
import Carbon.Icons.IconLogoMedium
import Carbon.Icons.IconLogoOpenshift
import Carbon.Icons.IconLogoPinterest
import Carbon.Icons.IconLogoPython
import Carbon.Icons.IconLogoQuora
import Carbon.Icons.IconLogoRScript
import Carbon.Icons.IconLogoSkype
import Carbon.Icons.IconLogoSlack
import Carbon.Icons.IconLogoSnapchat
import Carbon.Icons.IconLogoTumblr
import Carbon.Icons.IconLogoTwitter
import Carbon.Icons.IconLogoVmware
import Carbon.Icons.IconLogoXing
import Carbon.Icons.IconLogoYelp
import Carbon.Icons.IconLogoYoutube
import Carbon.Icons.IconLogout
import Carbon.Icons.IconLoop
import Carbon.Icons.IconMacCommand
import Carbon.Icons.IconMacOption
import Carbon.Icons.IconMacShift
import Carbon.Icons.IconMachineLearning
import Carbon.Icons.IconMachineLearningModel
import Carbon.Icons.IconMagicWand
import Carbon.Icons.IconMagicWandFilled
import Carbon.Icons.IconWatsonHealthMagnify
import Carbon.Icons.IconMailAll
import Carbon.Icons.IconMailReply
import Carbon.Icons.IconWatsonHealthMammogram
import Carbon.Icons.IconManageProtection
import Carbon.Icons.IconManagedSolutions
import Carbon.Icons.IconMap
import Carbon.Icons.IconMapBoundary
import Carbon.Icons.IconMarineWarning
import Carbon.Icons.IconMathCurve
import Carbon.Icons.IconQMatrix
import Carbon.Icons.IconMaximize
import Carbon.Icons.IconMedication
import Carbon.Icons.IconMedicationAlert
import Carbon.Icons.IconMedicationReminder
import Carbon.Icons.IconMenu
import Carbon.Icons.IconMeter
import Carbon.Icons.IconMeterAlt
import Carbon.Icons.IconMicrophone
import Carbon.Icons.IconMicrophoneFilled
import Carbon.Icons.IconMicrophoneOff
import Carbon.Icons.IconMicrophoneOffFilled
import Carbon.Icons.IconMicroscope
import Carbon.Icons.IconMigrate
import Carbon.Icons.IconMigrateAlt
import Carbon.Icons.IconMilestone
import Carbon.Icons.IconMinimize
import Carbon.Icons.IconMisuse
import Carbon.Icons.IconMisuseAlt
import Carbon.Icons.IconMisuseOutline
import Carbon.Icons.IconMixedRainHail
import Carbon.Icons.IconMobile
import Carbon.Icons.IconMobileAdd
import Carbon.Icons.IconMobileAudio
import Carbon.Icons.IconMobileCheck
import Carbon.Icons.IconMobileDownload
import Carbon.Icons.IconMobileLandscape
import Carbon.Icons.IconModel
import Carbon.Icons.IconModelAlt
import Carbon.Icons.IconModelReference
import Carbon.Icons.IconModelBuilder
import Carbon.Icons.IconModelBuilderReference
import Carbon.Icons.IconMoney
import Carbon.Icons.IconMonster
import Carbon.Icons.IconMonument
import Carbon.Icons.IconMoon
import Carbon.Icons.IconMoonrise
import Carbon.Icons.IconMoonset
import Carbon.Icons.IconMostlyCloudy
import Carbon.Icons.IconMostlyCloudyNight
import Carbon.Icons.IconMountain
import Carbon.Icons.IconMov
import Carbon.Icons.IconMove
import Carbon.Icons.IconMovement
import Carbon.Icons.IconMp3
import Carbon.Icons.IconMp4
import Carbon.Icons.IconMpeg
import Carbon.Icons.IconMpg2
import Carbon.Icons.IconMusic
import Carbon.Icons.IconMusicAdd
import Carbon.Icons.IconMusicRemove
import Carbon.Icons.IconNameSpace
import Carbon.Icons.IconNavaidCivil
import Carbon.Icons.IconNavaidDme
import Carbon.Icons.IconNavaidHelipad
import Carbon.Icons.IconNavaidMilitary
import Carbon.Icons.IconNavaidMilitaryCivil
import Carbon.Icons.IconNavaidNdb
import Carbon.Icons.IconNavaidNdbDme
import Carbon.Icons.IconNavaidPrivate
import Carbon.Icons.IconNavaidSeaplane
import Carbon.Icons.IconNavaidTacan
import Carbon.Icons.IconNavaidVhfor
import Carbon.Icons.IconNavaidVor
import Carbon.Icons.IconNavaidVordme
import Carbon.Icons.IconNavaidVortac
import Carbon.Icons.IconNetwork_1
import Carbon.Icons.IconNetwork_2
import Carbon.Icons.IconNetwork_3
import Carbon.Icons.IconNetwork_3Reference
import Carbon.Icons.IconNetwork_4
import Carbon.Icons.IconNewTab
import Carbon.Icons.IconNextFilled
import Carbon.Icons.IconNextOutline
import Carbon.Icons.IconNoImage
import Carbon.Icons.IconNoTicket
import Carbon.Icons.IconNominal
import Carbon.Icons.IconWatsonHealthNominate
import Carbon.Icons.IconNonCertified
import Carbon.Icons.IconNoodleBowl
import Carbon.Icons.IconNotAvailable
import Carbon.Icons.IconNotSent
import Carbon.Icons.IconNotSentFilled
import Carbon.Icons.IconNotebook
import Carbon.Icons.IconNotebookReference
import Carbon.Icons.IconNotification
import Carbon.Icons.IconNotificationFilled
import Carbon.Icons.IconNotificationNew
import Carbon.Icons.IconNotificationOff
import Carbon.Icons.IconNotificationOffFilled
import Carbon.Icons.IconNumber_0
import Carbon.Icons.IconNumber_1
import Carbon.Icons.IconNumber_2
import Carbon.Icons.IconNumber_3
import Carbon.Icons.IconNumber_4
import Carbon.Icons.IconNumber_5
import Carbon.Icons.IconNumber_6
import Carbon.Icons.IconNumber_7
import Carbon.Icons.IconNumber_8
import Carbon.Icons.IconNumber_9
import Carbon.Icons.IconNumberSmall_0
import Carbon.Icons.IconNumberSmall_1
import Carbon.Icons.IconNumberSmall_2
import Carbon.Icons.IconNumberSmall_3
import Carbon.Icons.IconNumberSmall_4
import Carbon.Icons.IconNumberSmall_5
import Carbon.Icons.IconNumberSmall_6
import Carbon.Icons.IconNumberSmall_7
import Carbon.Icons.IconNumberSmall_8
import Carbon.Icons.IconNumberSmall_9
import Carbon.Icons.IconObjectStorage
import Carbon.Icons.IconObservedHail
import Carbon.Icons.IconObservedLightning
import Carbon.Icons.IconOmega
import Carbon.Icons.IconOpacity
import Carbon.Icons.IconOpenPanelBottom
import Carbon.Icons.IconOpenPanelFilledBottom
import Carbon.Icons.IconOpenPanelFilledLeft
import Carbon.Icons.IconOpenPanelFilledRight
import Carbon.Icons.IconOpenPanelFilledTop
import Carbon.Icons.IconOpenPanelLeft
import Carbon.Icons.IconOpenPanelRight
import Carbon.Icons.IconOpenPanelTop
import Carbon.Icons.IconQOperation
import Carbon.Icons.IconQOperationGauge
import Carbon.Icons.IconQOperationIf
import Carbon.Icons.IconOperationsField
import Carbon.Icons.IconOperationsRecord
import Carbon.Icons.IconOrdinal
import Carbon.Icons.IconOutage
import Carbon.Icons.IconOutlookSevere
import Carbon.Icons.IconOverflowMenuHorizontal
import Carbon.Icons.IconOverflowMenuVertical
import Carbon.Icons.IconOverlay
import Carbon.Icons.IconPackage
import Carbon.Icons.IconPageFirst
import Carbon.Icons.IconPageLast
import Carbon.Icons.IconPageBreak
import Carbon.Icons.IconPageNumber
import Carbon.Icons.IconWatsonHealthPageScroll
import Carbon.Icons.IconPaintBrush
import Carbon.Icons.IconPaintBrushAlt
import Carbon.Icons.IconPalmTree
import Carbon.Icons.IconPanHorizontal
import Carbon.Icons.IconPanVertical
import Carbon.Icons.IconPanelExpansion
import Carbon.Icons.IconParagraph
import Carbon.Icons.IconParentChild
import Carbon.Icons.IconPartlyCloudy
import Carbon.Icons.IconPartlyCloudyNight
import Carbon.Icons.IconPartnership
import Carbon.Icons.IconPassengerDrinks
import Carbon.Icons.IconPassengerPlus
import Carbon.Icons.IconPassword
import Carbon.Icons.IconPaste
import Carbon.Icons.IconPause
import Carbon.Icons.IconPauseFilled
import Carbon.Icons.IconPauseOutline
import Carbon.Icons.IconPauseOutlineFilled
import Carbon.Icons.IconPauseFuture
import Carbon.Icons.IconPausePast
import Carbon.Icons.IconPdf
import Carbon.Icons.IconPdfReference
import Carbon.Icons.IconPedestrian
import Carbon.Icons.IconPedestrianFamily
import Carbon.Icons.IconPedestrianChild
import Carbon.Icons.IconPen
import Carbon.Icons.IconPenFountain
import Carbon.Icons.IconPending
import Carbon.Icons.IconPendingFilled
import Carbon.Icons.IconPercentage
import Carbon.Icons.IconPercentageFilled
import Carbon.Icons.IconPerson
import Carbon.Icons.IconPersonFavorite
import Carbon.Icons.IconPest
import Carbon.Icons.IconWatsonHealthPetImageB
import Carbon.Icons.IconWatsonHealthPetImageO
import Carbon.Icons.IconPhone
import Carbon.Icons.IconPhoneBlock
import Carbon.Icons.IconPhoneBlockFilled
import Carbon.Icons.IconPhoneFilled
import Carbon.Icons.IconPhoneIncoming
import Carbon.Icons.IconPhoneIncomingFilled
import Carbon.Icons.IconPhoneOff
import Carbon.Icons.IconPhoneOffFilled
import Carbon.Icons.IconPhoneOutgoing
import Carbon.Icons.IconPhoneOutgoingFilled
import Carbon.Icons.IconPhoneVoice
import Carbon.Icons.IconPhoneVoiceFilled
import Carbon.Icons.IconPhraseSentiment
import Carbon.Icons.IconPicnicArea
import Carbon.Icons.IconPiggyBank
import Carbon.Icons.IconPills
import Carbon.Icons.IconPillsAdd
import Carbon.Icons.IconPillsSubtract
import Carbon.Icons.IconPin
import Carbon.Icons.IconPinFilled
import Carbon.Icons.IconPlane
import Carbon.Icons.IconPlanePrivate
import Carbon.Icons.IconPlaneSea
import Carbon.Icons.IconPlay
import Carbon.Icons.IconPlayFilled
import Carbon.Icons.IconPlayFilledAlt
import Carbon.Icons.IconPlayOutline
import Carbon.Icons.IconPlayOutlineFilled
import Carbon.Icons.IconPlaylist
import Carbon.Icons.IconPlug
import Carbon.Icons.IconPlugFilled
import Carbon.Icons.IconPng
import Carbon.Icons.IconWatsonHealthPointerText
import Carbon.Icons.IconPolice
import Carbon.Icons.IconPolicy
import Carbon.Icons.IconPopup
import Carbon.Icons.IconPortfolio
import Carbon.Icons.IconPower
import Carbon.Icons.IconPpt
import Carbon.Icons.IconPresentationFile
import Carbon.Icons.IconPressure
import Carbon.Icons.IconPressureFilled
import Carbon.Icons.IconPreviousFilled
import Carbon.Icons.IconPreviousOutline
import Carbon.Icons.IconPrinter
import Carbon.Icons.IconProduct
import Carbon.Icons.IconProgressBar
import Carbon.Icons.IconProgressBarRound
import Carbon.Icons.IconPurchase
import Carbon.Icons.IconQqPlot
import Carbon.Icons.IconQrCode
import Carbon.Icons.IconQuadrantPlot
import Carbon.Icons.IconQuery
import Carbon.Icons.IconQueryQueue
import Carbon.Icons.IconQueued
import Carbon.Icons.IconQuotes
import Carbon.Icons.IconRadar
import Carbon.Icons.IconRadarEnhanced
import Carbon.Icons.IconRadarWeather
import Carbon.Icons.IconRadio
import Carbon.Icons.IconRadioButton
import Carbon.Icons.IconRadioButtonChecked
import Carbon.Icons.IconRain
import Carbon.Icons.IconRainDrizzle
import Carbon.Icons.IconRainHeavy
import Carbon.Icons.IconRainScattered
import Carbon.Icons.IconRainScatteredNight
import Carbon.Icons.IconRainDrop
import Carbon.Icons.IconRaw
import Carbon.Icons.IconReceipt
import Carbon.Icons.IconRecentlyViewed
import Carbon.Icons.IconRecommend
import Carbon.Icons.IconRecording
import Carbon.Icons.IconRecordingFilled
import Carbon.Icons.IconRecordingFilledAlt
import Carbon.Icons.IconRedo
import Carbon.Icons.IconRefEvapotranspiration
import Carbon.Icons.IconReflectHorizontal
import Carbon.Icons.IconReflectVertical
import Carbon.Icons.IconWatsonHealthRegionAnalysisArea
import Carbon.Icons.IconWatsonHealthRegionAnalysisVolume
import Carbon.Icons.IconWatsonHealthRegistration
import Carbon.Icons.IconReminder
import Carbon.Icons.IconReminderMedical
import Carbon.Icons.IconRenew
import Carbon.Icons.IconRepeat
import Carbon.Icons.IconRepeatOne
import Carbon.Icons.IconReply
import Carbon.Icons.IconReplyAll
import Carbon.Icons.IconReport
import Carbon.Icons.IconReportData
import Carbon.Icons.IconRequestQuote
import Carbon.Icons.IconResearchBlochSphere
import Carbon.Icons.IconResearchHintonPlot
import Carbon.Icons.IconResearchMatrix
import Carbon.Icons.IconReset
import Carbon.Icons.IconResetAlt
import Carbon.Icons.IconRestart
import Carbon.Icons.IconRestaurant
import Carbon.Icons.IconRestaurantFine
import Carbon.Icons.IconRewind_10
import Carbon.Icons.IconRewind_30
import Carbon.Icons.IconRewind_5
import Carbon.Icons.IconRoad
import Carbon.Icons.IconRoadWeather
import Carbon.Icons.IconRoadmap
import Carbon.Icons.IconRocket
import Carbon.Icons.IconRotate
import Carbon.Icons.IconWatsonHealthRotate_180
import Carbon.Icons.IconWatsonHealthRotate_360
import Carbon.Icons.IconRotateClockwise
import Carbon.Icons.IconRotateClockwiseAlt
import Carbon.Icons.IconRotateClockwiseAltFilled
import Carbon.Icons.IconRotateClockwiseFilled
import Carbon.Icons.IconRotateCounterclockwise
import Carbon.Icons.IconRotateCounterclockwiseAlt
import Carbon.Icons.IconRotateCounterclockwiseAltFilled
import Carbon.Icons.IconRotateCounterclockwiseFilled
import Carbon.Icons.IconRow
import Carbon.Icons.IconRowCollapse
import Carbon.Icons.IconRowDelete
import Carbon.Icons.IconRowExpand
import Carbon.Icons.IconRowInsert
import Carbon.Icons.IconRss
import Carbon.Icons.IconRule
import Carbon.Icons.IconRuler
import Carbon.Icons.IconRulerAlt
import Carbon.Icons.IconRun
import Carbon.Icons.IconQS
import Carbon.Icons.IconQSAlt
import Carbon.Icons.IconSailboatCoastal
import Carbon.Icons.IconSailboatOffshore
import Carbon.Icons.IconSankeyDiagram
import Carbon.Icons.IconSankeyDiagramAlt
import Carbon.Icons.IconSatellite
import Carbon.Icons.IconSatelliteRadar
import Carbon.Icons.IconSatelliteWeather
import Carbon.Icons.IconSave
import Carbon.Icons.IconWatsonHealthSaveAnnotation
import Carbon.Icons.IconWatsonHealthSaveImage
import Carbon.Icons.IconSaveModel
import Carbon.Icons.IconWatsonHealthSaveSeries
import Carbon.Icons.IconScale
import Carbon.Icons.IconScales
import Carbon.Icons.IconScalesTipped
import Carbon.Icons.IconScalpel
import Carbon.Icons.IconWatsonHealthScalpelCursor
import Carbon.Icons.IconWatsonHealthScalpelLasso
import Carbon.Icons.IconWatsonHealthScalpelSelect
import Carbon.Icons.IconScan
import Carbon.Icons.IconScatterMatrix
import Carbon.Icons.IconSchematics
import Carbon.Icons.IconScooter
import Carbon.Icons.IconScooterFront
import Carbon.Icons.IconScreen
import Carbon.Icons.IconScreenOff
import Carbon.Icons.IconScript
import Carbon.Icons.IconScriptReference
import Carbon.Icons.IconSdk
import Carbon.Icons.IconSearch
import Carbon.Icons.IconSecurity
import Carbon.Icons.IconSelect_01
import Carbon.Icons.IconSelect_02
import Carbon.Icons.IconSend
import Carbon.Icons.IconSendAlt
import Carbon.Icons.IconSendAltFilled
import Carbon.Icons.IconSendFilled
import Carbon.Icons.IconSendToBack
import Carbon.Icons.IconServiceDesk
import Carbon.Icons.IconSettings
import Carbon.Icons.IconSettingsAdjust
import Carbon.Icons.IconSettingsCheck
import Carbon.Icons.IconShapeExcept
import Carbon.Icons.IconShapeExclude
import Carbon.Icons.IconShapeIntersect
import Carbon.Icons.IconShapeJoin
import Carbon.Icons.IconShapeUnite
import Carbon.Icons.IconShare
import Carbon.Icons.IconShareKnowledge
import Carbon.Icons.IconShoppingBag
import Carbon.Icons.IconShoppingCart
import Carbon.Icons.IconShoppingCartArrowDown
import Carbon.Icons.IconShoppingCartArrowUp
import Carbon.Icons.IconShoppingCartClear
import Carbon.Icons.IconShoppingCartError
import Carbon.Icons.IconShoppingCartMinus
import Carbon.Icons.IconShoppingCartPlus
import Carbon.Icons.IconShoppingCatalog
import Carbon.Icons.IconShrinkScreen
import Carbon.Icons.IconShrinkScreenFilled
import Carbon.Icons.IconShuffle
import Carbon.Icons.IconShuttle
import Carbon.Icons.IconSigma
import Carbon.Icons.IconSignalStrength
import Carbon.Icons.IconSkillLevel
import Carbon.Icons.IconSkillLevelAdvanced
import Carbon.Icons.IconSkillLevelBasic
import Carbon.Icons.IconSkillLevelIntermediate
import Carbon.Icons.IconSkipBack
import Carbon.Icons.IconSkipBackFilled
import Carbon.Icons.IconSkipBackOutline
import Carbon.Icons.IconSkipBackOutlineFilled
import Carbon.Icons.IconSkipBackOutlineSolid
import Carbon.Icons.IconSkipBackSolidFilled
import Carbon.Icons.IconSkipForward
import Carbon.Icons.IconSkipForwardFilled
import Carbon.Icons.IconSkipForwardOutline
import Carbon.Icons.IconSkipForwardOutlineFilled
import Carbon.Icons.IconSkipForwardOutlineSolid
import Carbon.Icons.IconSkipForwardSolidFilled
import Carbon.Icons.IconSleet
import Carbon.Icons.IconSmell
import Carbon.Icons.IconSmoke
import Carbon.Icons.IconWatsonHealthSmoothing
import Carbon.Icons.IconWatsonHealthSmoothingCursor
import Carbon.Icons.IconSnooze
import Carbon.Icons.IconSnow
import Carbon.Icons.IconSnowBlizzard
import Carbon.Icons.IconSnowHeavy
import Carbon.Icons.IconSnowScattered
import Carbon.Icons.IconSnowScatteredNight
import Carbon.Icons.IconSnowDensity
import Carbon.Icons.IconSnowflake
import Carbon.Icons.IconSoccer
import Carbon.Icons.IconSoilMoisture
import Carbon.Icons.IconSoilMoistureField
import Carbon.Icons.IconSoilMoistureGlobal
import Carbon.Icons.IconSoilTemperature
import Carbon.Icons.IconSoilTemperatureField
import Carbon.Icons.IconSoilTemperatureGlobal
import Carbon.Icons.IconSpellCheck
import Carbon.Icons.IconWatsonHealthSpineLabel
import Carbon.Icons.IconSplit
import Carbon.Icons.IconWatsonHealthSplitDiscard
import Carbon.Icons.IconSplitScreen
import Carbon.Icons.IconSprayPaint
import Carbon.Icons.IconSprout
import Carbon.Icons.IconSql
import Carbon.Icons.IconStackLimitation
import Carbon.Icons.IconWatsonHealthStackedMove
import Carbon.Icons.IconWatsonHealthStackedScrolling_1
import Carbon.Icons.IconWatsonHealthStackedScrolling_2
import Carbon.Icons.IconStamp
import Carbon.Icons.IconStar
import Carbon.Icons.IconStarFilled
import Carbon.Icons.IconStarHalf
import Carbon.Icons.IconStarReview
import Carbon.Icons.IconStayInside
import Carbon.Icons.IconStemLeafPlot
import Carbon.Icons.IconStethoscope
import Carbon.Icons.IconStop
import Carbon.Icons.IconStopFilled
import Carbon.Icons.IconStopFilledAlt
import Carbon.Icons.IconStopOutline
import Carbon.Icons.IconStopOutlineFilled
import Carbon.Icons.IconStopSign
import Carbon.Icons.IconStopSignFilled
import Carbon.Icons.IconStoragePool
import Carbon.Icons.IconStorageRequest
import Carbon.Icons.IconStore
import Carbon.Icons.IconStormTracker
import Carbon.Icons.IconStrawberry
import Carbon.Icons.IconWatsonHealthStressBreathEditor
import Carbon.Icons.IconStringInteger
import Carbon.Icons.IconStringText
import Carbon.Icons.IconWatsonHealthStudyNext
import Carbon.Icons.IconWatsonHealthStudyPrevious
import Carbon.Icons.IconWatsonHealthStudySkip
import Carbon.Icons.IconWatsonHealthSubVolume
import Carbon.Icons.IconSubtract
import Carbon.Icons.IconSubtractAlt
import Carbon.Icons.IconSummaryKpi
import Carbon.Icons.IconSun
import Carbon.Icons.IconSunny
import Carbon.Icons.IconSunrise
import Carbon.Icons.IconSunset
import Carbon.Icons.IconSvg
import Carbon.Icons.IconSwim
import Carbon.Icons.IconSwitcher
import Carbon.Icons.IconSysProvision
import Carbon.Icons.IconQT
import Carbon.Icons.IconQTAlt
import Carbon.Icons.IconTable
import Carbon.Icons.IconTableBuilt
import Carbon.Icons.IconTableSplit
import Carbon.Icons.IconTableOfContents
import Carbon.Icons.IconTablet
import Carbon.Icons.IconTabletLandscape
import Carbon.Icons.IconTag
import Carbon.Icons.IconTagEdit
import Carbon.Icons.IconTagGroup
import Carbon.Icons.IconTask
import Carbon.Icons.IconTaskView
import Carbon.Icons.IconTaste
import Carbon.Icons.IconTaxi
import Carbon.Icons.IconTemperature
import Carbon.Icons.IconTemperatureFeelsLike
import Carbon.Icons.IconTemperatureFrigid
import Carbon.Icons.IconTemperatureHot
import Carbon.Icons.IconTemperatureInversion
import Carbon.Icons.IconTemperatureMax
import Carbon.Icons.IconTemperatureMin
import Carbon.Icons.IconTemperatureWater
import Carbon.Icons.IconTemplate
import Carbon.Icons.IconTennis
import Carbon.Icons.IconTennisBall
import Carbon.Icons.IconTerm
import Carbon.Icons.IconTerminal
import Carbon.Icons.IconTextAlignCenter
import Carbon.Icons.IconTextAlignJustify
import Carbon.Icons.IconTextAlignLeft
import Carbon.Icons.IconTextAlignMixed
import Carbon.Icons.IconTextAlignRight
import Carbon.Icons.IconTextAllCaps
import Carbon.Icons.IconTextBold
import Carbon.Icons.IconTextColor
import Carbon.Icons.IconTextCreation
import Carbon.Icons.IconTextFill
import Carbon.Icons.IconTextFootnote
import Carbon.Icons.IconTextHighlight
import Carbon.Icons.IconTextIndent
import Carbon.Icons.IconTextIndentLess
import Carbon.Icons.IconTextIndentMore
import Carbon.Icons.IconTextItalic
import Carbon.Icons.IconTextKerning
import Carbon.Icons.IconTextLeading
import Carbon.Icons.IconTextLineSpacing
import Carbon.Icons.IconTextNewLine
import Carbon.Icons.IconTextScale
import Carbon.Icons.IconTextSelection
import Carbon.Icons.IconTextSmallCaps
import Carbon.Icons.IconTextStrikethrough
import Carbon.Icons.IconTextSubscript
import Carbon.Icons.IconTextSuperscript
import Carbon.Icons.IconTextTracking
import Carbon.Icons.IconTextUnderline
import Carbon.Icons.IconTextVerticalAlignment
import Carbon.Icons.IconTextWrap
import Carbon.Icons.IconWatsonHealthTextAnnotationToggle
import Carbon.Icons.IconTextLink
import Carbon.Icons.IconTextLinkAnalysis
import Carbon.Icons.IconTextMining
import Carbon.Icons.IconTextMiningApplier
import Carbon.Icons.IconTheater
import Carbon.Icons.IconThisSideUp
import Carbon.Icons.IconWatsonHealthThreshold
import Carbon.Icons.IconThumbnail_1
import Carbon.Icons.IconThumbnail_2
import Carbon.Icons.IconWatsonHealthThumbnailPreview
import Carbon.Icons.IconThumbsDown
import Carbon.Icons.IconThumbsUp
import Carbon.Icons.IconThunderstorm
import Carbon.Icons.IconThunderstormScattered
import Carbon.Icons.IconThunderstormScatteredNight
import Carbon.Icons.IconThunderstormSevere
import Carbon.Icons.IconThunderstormStrong
import Carbon.Icons.IconTicket
import Carbon.Icons.IconTides
import Carbon.Icons.IconTif
import Carbon.Icons.IconTime
import Carbon.Icons.IconTimePlot
import Carbon.Icons.IconTimer
import Carbon.Icons.IconToolBox
import Carbon.Icons.IconTools
import Carbon.Icons.IconToolsAlt
import Carbon.Icons.IconTornado
import Carbon.Icons.IconTornadoWarning
import Carbon.Icons.IconTouch_1
import Carbon.Icons.IconTouch_2
import Carbon.Icons.IconTouchInteraction
import Carbon.Icons.IconTrafficEvent
import Carbon.Icons.IconTrafficFlow
import Carbon.Icons.IconTrafficFlowIncident
import Carbon.Icons.IconTrafficIncident
import Carbon.Icons.IconTrafficWeatherIncident
import Carbon.Icons.IconTrafficCone
import Carbon.Icons.IconTrain
import Carbon.Icons.IconTrainHeart
import Carbon.Icons.IconTrainTicket
import Carbon.Icons.IconTrainTime
import Carbon.Icons.IconTram
import Carbon.Icons.IconTransgender
import Carbon.Icons.IconTranslate
import Carbon.Icons.IconTranspose
import Carbon.Icons.IconTrashCan
import Carbon.Icons.IconTree
import Carbon.Icons.IconTreeView
import Carbon.Icons.IconTreeViewAlt
import Carbon.Icons.IconTrophy
import Carbon.Icons.IconTrophyFilled
import Carbon.Icons.IconTropicalStorm
import Carbon.Icons.IconTropicalStormModelTracks
import Carbon.Icons.IconTropicalStormTracks
import Carbon.Icons.IconTropicalWarning
import Carbon.Icons.IconTsunami
import Carbon.Icons.IconTsv
import Carbon.Icons.IconTwoPersonLift
import Carbon.Icons.IconTxt
import Carbon.Icons.IconTxtReference
import Carbon.Icons.IconTypePattern
import Carbon.Icons.IconTypes
import Carbon.Icons.IconQU1
import Carbon.Icons.IconQU2
import Carbon.Icons.IconQU3
import Carbon.Icons.IconUmbrella
import Carbon.Icons.IconUndefined
import Carbon.Icons.IconUndefinedFilled
import Carbon.Icons.IconUndo
import Carbon.Icons.IconUnknown
import Carbon.Icons.IconUnknownFilled
import Carbon.Icons.IconUnlink
import Carbon.Icons.IconUnlocked
import Carbon.Icons.IconUpToTop
import Carbon.Icons.IconUpgrade
import Carbon.Icons.IconUpload
import Carbon.Icons.IconUsb
import Carbon.Icons.IconUser
import Carbon.Icons.IconUserActivity
import Carbon.Icons.IconUserAdmin
import Carbon.Icons.IconUserAvatar
import Carbon.Icons.IconUserAvatarFilled
import Carbon.Icons.IconUserAvatarFilledAlt
import Carbon.Icons.IconUserCertification
import Carbon.Icons.IconUserData
import Carbon.Icons.IconUserFavorite
import Carbon.Icons.IconUserFavoriteAlt
import Carbon.Icons.IconUserFavoriteAltFilled
import Carbon.Icons.IconUserFilled
import Carbon.Icons.IconUserFollow
import Carbon.Icons.IconUserIdentification
import Carbon.Icons.IconUserMultiple
import Carbon.Icons.IconUserOnline
import Carbon.Icons.IconUserProfile
import Carbon.Icons.IconUserRole
import Carbon.Icons.IconUserSimulation
import Carbon.Icons.IconUserSpeaker
import Carbon.Icons.IconUserXRay
import Carbon.Icons.IconUserProfileAlt
import Carbon.Icons.IconUvIndex
import Carbon.Icons.IconUvIndexAlt
import Carbon.Icons.IconUvIndexFilled
import Carbon.Icons.IconVan
import Carbon.Icons.IconVideo
import Carbon.Icons.IconVideoAdd
import Carbon.Icons.IconVideoChat
import Carbon.Icons.IconVideoFilled
import Carbon.Icons.IconVideoOff
import Carbon.Icons.IconVideoOffFilled
import Carbon.Icons.IconView
import Carbon.Icons.IconViewFilled
import Carbon.Icons.IconViewMode_1
import Carbon.Icons.IconViewMode_2
import Carbon.Icons.IconViewOff
import Carbon.Icons.IconViewOffFilled
import Carbon.Icons.IconViewNext
import Carbon.Icons.IconVirtualColumn
import Carbon.Icons.IconVirtualColumnKey
import Carbon.Icons.IconVirtualMachine
import Carbon.Icons.IconVirtualPrivateCloud
import Carbon.Icons.IconVirtualPrivateCloudAlt
import Carbon.Icons.IconVisualRecognition
import Carbon.Icons.IconVmdkDisk
import Carbon.Icons.IconVoicemail
import Carbon.Icons.IconVolumeDown
import Carbon.Icons.IconVolumeDownFilled
import Carbon.Icons.IconVolumeMute
import Carbon.Icons.IconVolumeMuteFilled
import Carbon.Icons.IconVolumeUp
import Carbon.Icons.IconVolumeUpFilled
import Carbon.Icons.IconVpn
import Carbon.Icons.IconWallet
import Carbon.Icons.IconWarning
import Carbon.Icons.IconWarningAlt
import Carbon.Icons.IconWarningAltFilled
import Carbon.Icons.IconWarningAltInverted
import Carbon.Icons.IconWarningAltInvertedFilled
import Carbon.Icons.IconWarningFilled
import Carbon.Icons.IconWarningHex
import Carbon.Icons.IconWarningHexFilled
import Carbon.Icons.IconWarningOther
import Carbon.Icons.IconWarningSquare
import Carbon.Icons.IconWarningSquareFilled
import Carbon.Icons.IconWatch
import Carbon.Icons.IconWatson
import Carbon.Icons.IconWatsonMachineLearning
import Carbon.Icons.IconWaveDirection
import Carbon.Icons.IconWaveHeight
import Carbon.Icons.IconWavePeriod
import Carbon.Icons.IconWeatherFrontCold
import Carbon.Icons.IconWeatherFrontStationary
import Carbon.Icons.IconWeatherFrontWarm
import Carbon.Icons.IconWeatherStation
import Carbon.Icons.IconWebsheet
import Carbon.Icons.IconWheat
import Carbon.Icons.IconWifi
import Carbon.Icons.IconWifiOff
import Carbon.Icons.IconWikis
import Carbon.Icons.IconWindGusts
import Carbon.Icons.IconWindStream
import Carbon.Icons.IconWatsonHealthWindowAuto
import Carbon.Icons.IconWatsonHealthWindowBase
import Carbon.Icons.IconWatsonHealthWindowOverlay
import Carbon.Icons.IconWatsonHealthWindowPreset
import Carbon.Icons.IconWindy
import Carbon.Icons.IconWindyDust
import Carbon.Icons.IconWindySnow
import Carbon.Icons.IconWindyStrong
import Carbon.Icons.IconWinterWarning
import Carbon.Icons.IconWintryMix
import Carbon.Icons.IconWirelessCheckout
import Carbon.Icons.IconWmv
import Carbon.Icons.IconWordCloud
import Carbon.Icons.IconWorkspace
import Carbon.Icons.IconWorkspaceImport
import Carbon.Icons.IconWorship
import Carbon.Icons.IconWorshipChristian
import Carbon.Icons.IconWorshipJewish
import Carbon.Icons.IconWorshipMuslim
import Carbon.Icons.IconQX
import Carbon.Icons.IconXAxis
import Carbon.Icons.IconXls
import Carbon.Icons.IconXml
import Carbon.Icons.IconQY
import Carbon.Icons.IconYAxis
import Carbon.Icons.IconQZ
import Carbon.Icons.IconZAxis
import Carbon.Icons.IconZip
import Carbon.Icons.IconZipReference
import Carbon.Icons.IconZoomIn
import Carbon.Icons.IconZoomInArea
import Carbon.Icons.IconZoomOut
import Carbon.Icons.IconZoomOutArea
import Carbon.Icons.IconZoomReset
import Carbon.Icons.IconWatsonHealthZoomPan
