{-# LANGUAGE OverloadedStrings #-}

module Carbon.Icons.IconChartTSne where

import Carbon.Svg

iconChartTSne32 :: Svg
iconChartTSne32 = Svg {svgName = "ChartTSne32", svgNamespace = "http://www.w3.org/2000/svg", svgViewBox = "0 0 32 32", svgFill = "currentColor", svgWidth = "32.0", svgHeight = "32.0", svgContent = [SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "20", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "28", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "14", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "28", svgCircleY = "4", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "22", svgCircleY = "6", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "28", svgCircleY = "10", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "20", svgCircleY = "12", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "28", svgCircleY = "22", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "26", svgCircleY = "28", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "20", svgCircleY = "26", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "22", svgCircleY = "20", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "16", svgCircleY = "4", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "4", svgCircleY = "24", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "4", svgCircleY = "16", svgCircleRadius = "2"})], svgTitle = Nothing}

iconChartTSne24 :: Svg
iconChartTSne24 = Svg {svgName = "ChartTSne24", svgNamespace = "http://www.w3.org/2000/svg", svgViewBox = "0 0 32 32", svgFill = "currentColor", svgWidth = "24.0", svgHeight = "24.0", svgContent = [SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "20", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "28", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "14", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "28", svgCircleY = "4", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "22", svgCircleY = "6", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "28", svgCircleY = "10", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "20", svgCircleY = "12", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "28", svgCircleY = "22", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "26", svgCircleY = "28", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "20", svgCircleY = "26", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "22", svgCircleY = "20", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "16", svgCircleY = "4", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "4", svgCircleY = "24", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "4", svgCircleY = "16", svgCircleRadius = "2"})], svgTitle = Nothing}

iconChartTSne20 :: Svg
iconChartTSne20 = Svg {svgName = "ChartTSne20", svgNamespace = "http://www.w3.org/2000/svg", svgViewBox = "0 0 32 32", svgFill = "currentColor", svgWidth = "20.0", svgHeight = "20.0", svgContent = [SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "20", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "28", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "14", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "28", svgCircleY = "4", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "22", svgCircleY = "6", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "28", svgCircleY = "10", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "20", svgCircleY = "12", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "28", svgCircleY = "22", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "26", svgCircleY = "28", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "20", svgCircleY = "26", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "22", svgCircleY = "20", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "16", svgCircleY = "4", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "4", svgCircleY = "24", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "4", svgCircleY = "16", svgCircleRadius = "2"})], svgTitle = Nothing}

iconChartTSne16 :: Svg
iconChartTSne16 = Svg {svgName = "ChartTSne16", svgNamespace = "http://www.w3.org/2000/svg", svgViewBox = "0 0 32 32", svgFill = "currentColor", svgWidth = "16.0", svgHeight = "16.0", svgContent = [SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "20", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "28", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "14", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "28", svgCircleY = "4", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "22", svgCircleY = "6", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "28", svgCircleY = "10", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "20", svgCircleY = "12", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "28", svgCircleY = "22", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "26", svgCircleY = "28", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "20", svgCircleY = "26", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "22", svgCircleY = "20", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "16", svgCircleY = "4", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "4", svgCircleY = "24", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "4", svgCircleY = "16", svgCircleRadius = "2"})], svgTitle = Nothing}