{-# LANGUAGE OverloadedStrings #-}

module Carbon.Icons.IconChartScatter where

import Carbon.Svg

iconChartScatter32 :: Svg
iconChartScatter32 = Svg {svgName = "ChartScatter32", svgNamespace = "http://www.w3.org/2000/svg", svgViewBox = "0 0 32 32", svgFill = "currentColor", svgWidth = "32.0", svgHeight = "32.0", svgContent = [SvgElementPath (SvgPath {svgPathD = "M30,30H4a2,2,0,0,1-2-2V2H4V28H30Z", svgPathFill = Nothing, svgPathDataIconPath = Nothing}),SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "22", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "14", svgCircleY = "15", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "22", svgCircleY = "15", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "26", svgCircleY = "6", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "14", svgCircleY = "8", svgCircleRadius = "2"})]}

iconChartScatter24 :: Svg
iconChartScatter24 = Svg {svgName = "ChartScatter24", svgNamespace = "http://www.w3.org/2000/svg", svgViewBox = "0 0 32 32", svgFill = "currentColor", svgWidth = "24.0", svgHeight = "24.0", svgContent = [SvgElementPath (SvgPath {svgPathD = "M30,30H4a2,2,0,0,1-2-2V2H4V28H30Z", svgPathFill = Nothing, svgPathDataIconPath = Nothing}),SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "22", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "14", svgCircleY = "15", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "22", svgCircleY = "15", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "26", svgCircleY = "6", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "14", svgCircleY = "8", svgCircleRadius = "2"})]}

iconChartScatter20 :: Svg
iconChartScatter20 = Svg {svgName = "ChartScatter20", svgNamespace = "http://www.w3.org/2000/svg", svgViewBox = "0 0 32 32", svgFill = "currentColor", svgWidth = "20.0", svgHeight = "20.0", svgContent = [SvgElementPath (SvgPath {svgPathD = "M30,30H4a2,2,0,0,1-2-2V2H4V28H30Z", svgPathFill = Nothing, svgPathDataIconPath = Nothing}),SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "22", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "14", svgCircleY = "15", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "22", svgCircleY = "15", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "26", svgCircleY = "6", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "14", svgCircleY = "8", svgCircleRadius = "2"})]}

iconChartScatter16 :: Svg
iconChartScatter16 = Svg {svgName = "ChartScatter16", svgNamespace = "http://www.w3.org/2000/svg", svgViewBox = "0 0 32 32", svgFill = "currentColor", svgWidth = "16.0", svgHeight = "16.0", svgContent = [SvgElementPath (SvgPath {svgPathD = "M30,30H4a2,2,0,0,1-2-2V2H4V28H30Z", svgPathFill = Nothing, svgPathDataIconPath = Nothing}),SvgElementCircle (SvgCircle {svgCircleX = "10", svgCircleY = "22", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "14", svgCircleY = "15", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "22", svgCircleY = "15", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "26", svgCircleY = "6", svgCircleRadius = "2"}),SvgElementCircle (SvgCircle {svgCircleX = "14", svgCircleY = "8", svgCircleRadius = "2"})]}